function queue = createMiniBatchQueue(imageStore, grades, batchSize, environment)
%CREATEMINIBATCHQUEUE Build a lazy queue with image and integer targets.

labelStore = arrayDatastore(single(grades(:) + 1), ...
    'OutputType', 'same');
combinedStore = combine(imageStore, labelStore);
queue = minibatchqueue(combinedStore, 2, ...
    'MiniBatchSize', batchSize, ...
    'MiniBatchFcn', @collateData, ...
    'OutputCast', {'single', 'single'}, ...
    'OutputAsDlarray', [true, true], ...
    'MiniBatchFormat', {'SSCB', 'CB'}, ...
    'OutputEnvironment', environment, ...
    'PartialMiniBatch', 'return');
end
