function queue = createMiniBatchQueue(imageStore, grades, batchSize, environment, varargin)
%CREATEMINIBATCHQUEUE Build a lazy queue with image and integer targets.
%   Optional fifth argument enables background prefetch so CPU-side
%   preprocessing overlaps GPU compute; delivery timing changes only.
%   Optional sixth argument enables train-only batch augmentation.

if nargin < 5
    dispatchInBackground = true;
else
    dispatchInBackground = logical(varargin{1});
end
if nargin < 6
    augment = false;
else
    augment = logical(varargin{2});
end

labelStore = arrayDatastore(single(grades(:) + 1), ...
    'OutputType', 'same');
combinedStore = combine(imageStore, labelStore);
queue = minibatchqueue(combinedStore, 2, ...
    'MiniBatchSize', batchSize, ...
    'MiniBatchFcn', @(imageCells, targetCells) ...
        collateData(imageCells, targetCells, augment), ...
    'OutputCast', {'single', 'single'}, ...
    'OutputAsDlarray', [true, true], ...
    'MiniBatchFormat', {'SSCB', 'CB'}, ...
    'OutputEnvironment', environment, ...
    'PartialMiniBatch', 'return', ...
    'DispatchInBackground', dispatchInBackground);
end
